export const GET_PHOTOS_REQUEST = 'GET_PHOTOS_REQUEST';
export const GET_PHOTOS_SUCCESS = 'GET_PHOTOS_SUCCESS';
export const GET_PHOTOS_ERROR = 'GET_PHOTOS_ERROR';

export const GET_PHOTO_REQUEST = 'GET_PHOTO_REQUEST';
export const GET_PHOTO_SUCCESS = 'GET_PHOTO_SUCCESS';
export const GET_PHOTO_ERROR = 'GET_PHOTO_ERROR';

export const EDIT_PHOTO_REQUEST = 'EDIT_PHOTO_REQUEST';
export const EDIT_PHOTO_SUCCESS = 'EDIT_PHOTO_SUCCESS';
export const EDIT_PHOTO_ERROR = 'EDIT_PHOTO_ERROR';

export const PHOTO_RESET = 'PHOTO_RESET';
